# version: '3.7'
# services:
#     postgres:
#         image: postgres:9.6
#         environment:
#             - POSTGRES_USER=airflow
#             - POSTGRES_PASSWORD=airflow
#             - POSTGRES_DB=airflow
#         ports: 
#             - 5432:5432
#         logging:
#             options:
#                 max-size: 10m
#                 max-file: "3"
#     pgadmin:
#         image: dpage/pgadmin4
#         environment: 
#             - PGADMIN_DEFAULT_EMAIL=your_email_here
#             - PGADMIN_DEFAULT_PASSWORD=your_password_here
#         ports: 
#             - "5050:80"

#             version: '3'

services:
    postgres-compose:
        image: postgres
        environment:
            POSTGRES_USERNAME: "postgres"
            POSTGRES_PASSWORD: "#L!pp@us2@18"
        ports:
            - "8050:8050"
        volumes:
            - /home/duducp/PostgreSQL:/var/lib/postgresql/data
        networks:
            - postgres-compose-network

    pgadmin-compose:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "postgres@email.com"
            PGADMIN_DEFAULT_PASSWORD: "postgres"
        ports:
            - "15432:80"
        depends_on:
            - postgres-compose
        networks:
            - postgres-compose-network

networks:
    postgres-compose-network:
        driver: bridge
